//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Parts.Main.DecryptPart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DecryptPartTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecryptPartTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Parts.Main.DecryptPart.DecryptPartTranslation", typeof(DecryptPartTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt the file.
        ///
        ///{0}.
        /// </summary>
        public static string DecryptCommandFails {
            get {
                return ResourceManager.GetString("DecryptCommandFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string DecryptCommandLabel {
            get {
                return ResourceManager.GetString("DecryptCommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted files to folder {0}..
        /// </summary>
        public static string DecryptCommandSucceeds {
            get {
                return ResourceManager.GetString("DecryptCommandSucceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt and unpack the Document Packer file..
        /// </summary>
        public static string DecryptCommandToolTip {
            get {
                return ResourceManager.GetString("DecryptCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been sent an encrypted Document Packer file? Decrypt the Document Packer file with your private key. View or save the decrypted files..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        public static string EncryptedFileDoesNotExist {
            get {
                return ResourceManager.GetString("EncryptedFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string EncryptedFileIsRequired {
            get {
                return ResourceManager.GetString("EncryptedFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Document Packer file.
        /// </summary>
        public static string EncryptedFileLabel {
            get {
                return ResourceManager.GetString("EncryptedFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the enrypted Document Packer file..
        /// </summary>
        public static string EncryptedFileToolTip {
            get {
                return ResourceManager.GetString("EncryptedFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.dp.
        /// </summary>
        public static string EncryptedFileWatermark {
            get {
                return ResourceManager.GetString("EncryptedFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string OutputFolderDoesNotExist {
            get {
                return ResourceManager.GetString("OutputFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder is required..
        /// </summary>
        public static string OutputFolderIsRequired {
            get {
                return ResourceManager.GetString("OutputFolderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of the encrypted file is extracted to this folder..
        /// </summary>
        public static string OutputFolderToolTip {
            get {
                return ResourceManager.GetString("OutputFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output folder.
        /// </summary>
        public static string OutputFolderWatermark {
            get {
                return ResourceManager.GetString("OutputFolderWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private RSA key is required..
        /// </summary>
        public static string PrivateRsaKeyIsRequired {
            get {
                return ResourceManager.GetString("PrivateRsaKeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private RSA Key.
        /// </summary>
        public static string PrivateRsaKeyLabel {
            get {
                return ResourceManager.GetString("PrivateRsaKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private RSA key to decrypt the Document Packer file..
        /// </summary>
        public static string PrivateRsaKeyToolTip {
            get {
                return ResourceManager.GetString("PrivateRsaKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private RSA key.
        /// </summary>
        public static string PrivateRsaKeyWatermark {
            get {
                return ResourceManager.GetString("PrivateRsaKeyWatermark", resourceCulture);
            }
        }
    }
}
