//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Parts.Main.CreateConfigurationPart.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateConfigurationPartTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateConfigurationPartTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Parts.Main.CreateConfigurationPart.Translations.CreateConfiguratio" +
                            "nPartTranslation", typeof(CreateConfigurationPartTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new configuration item..
        /// </summary>
        public static string AddConfigurationItemToolTip {
            get {
                return ResourceManager.GetString("AddConfigurationItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ConfigurationItemTypeFile {
            get {
                return ResourceManager.GetString("ConfigurationItemTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the Item.
        /// </summary>
        public static string ConfigurationItemTypeLabel {
            get {
                return ResourceManager.GetString("ConfigurationItemTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ConfigurationItemTypeText {
            get {
                return ResourceManager.GetString("ConfigurationItemTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether the secret data is a file or plaintext..
        /// </summary>
        public static string ConfigurationItemTypeToolTip {
            get {
                return ResourceManager.GetString("ConfigurationItemTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string ConfigurationItemTypeWatermark {
            get {
                return ResourceManager.GetString("ConfigurationItemTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the configuration item..
        /// </summary>
        public static string DeleteConfigurationItemCommandToolTip {
            get {
                return ResourceManager.GetString("DeleteConfigurationItemCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description is required..
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the new Document Packer configuration. The description will be displayed when encrypting files..
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return ResourceManager.GetString("DescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my secret data collection.
        /// </summary>
        public static string DescriptionWatermark {
            get {
                return ResourceManager.GetString("DescriptionWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA keys are generated..
        /// </summary>
        public static string GenerateRsaKeysCommandCancelInfoText {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandCancelInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenerateRsaKeysCommandCancelLabel {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborts the current process..
        /// </summary>
        public static string GenerateRsaKeysCommandCancelToolTip {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandCancelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenerateRsaKeysCommandCaption {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new pair of RSA private and public keys..
        /// </summary>
        public static string GenerateRsaKeysCommandToolTip {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooooops...an unexpected error occured: .
        /// </summary>
        public static string GenerateRsaKeysCommandUnknownError {
            get {
                return ResourceManager.GetString("GenerateRsaKeysCommandUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id contains invalid characters.
        /// </summary>
        public static string IdConatainsInvalidCharacters {
            get {
                return ResourceManager.GetString("IdConatainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name used multiple times..
        /// </summary>
        public static string IdDuplicate {
            get {
                return ResourceManager.GetString("IdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id is required.
        /// </summary>
        public static string IdIsRequired {
            get {
                return ResourceManager.GetString("IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string IdLabel {
            get {
                return ResourceManager.GetString("IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name or ID for the entry. This name will be used as the file name when decrypting the Document Packer entry. These characters must not be used: &quot;, &lt;, &gt;, |, :, *, ?, \, /&quot;.
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecretFile.
        /// </summary>
        public static string IdWatermark {
            get {
                return ResourceManager.GetString("IdWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string IsRequiredLabel {
            get {
                return ResourceManager.GetString("IsRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates wheather the entry is required or optional..
        /// </summary>
        public static string IsRequiredToolTip {
            get {
                return ResourceManager.GetString("IsRequiredToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description is required..
        /// </summary>
        public static string ItemDescriptionIsRequired {
            get {
                return ResourceManager.GetString("ItemDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ItemDescriptionLabel {
            get {
                return ResourceManager.GetString("ItemDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short description of the configuration item..
        /// </summary>
        public static string ItemDescriptionToolTip {
            get {
                return ResourceManager.GetString("ItemDescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains the secrets of the world..
        /// </summary>
        public static string ItemDescriptionWatermark {
            get {
                return ResourceManager.GetString("ItemDescriptionWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to add..
        /// </summary>
        public static string OpenFileDialogToolTip {
            get {
                return ResourceManager.GetString("OpenFileDialogToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist..
        /// </summary>
        public static string OutputFolderDoesNotExist {
            get {
                return ResourceManager.GetString("OutputFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the output folder..
        /// </summary>
        public static string OutputFolderIsRequired {
            get {
                return ResourceManager.GetString("OutputFolderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder of the Document Packer configuration file..
        /// </summary>
        public static string OutputFolderToolTip {
            get {
                return ResourceManager.GetString("OutputFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\data\secret_data.
        /// </summary>
        public static string OutputFolderWatermark {
            get {
                return ResourceManager.GetString("OutputFolderWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password is required..
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a password to protect the configuration files..
        /// </summary>
        public static string PasswordToolTip {
            get {
                return ResourceManager.GetString("PasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yt70?5*DLFS2.
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists..
        /// </summary>
        public static string PrivateOutputFileDoesExist {
            get {
                return ResourceManager.GetString("PrivateOutputFileDoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predefined file extension of the private Document Packer configuration file..
        /// </summary>
        public static string PrivateOutputFileExtensionToolTip {
            get {
                return ResourceManager.GetString("PrivateOutputFileExtensionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string PrivateOutputFileIsRequired {
            get {
                return ResourceManager.GetString("PrivateOutputFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Output File.
        /// </summary>
        public static string PrivateOutputFileLabel {
            get {
                return ResourceManager.GetString("PrivateOutputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the private Document Packer configuration file..
        /// </summary>
        public static string PrivateOutputFileToolTip {
            get {
                return ResourceManager.GetString("PrivateOutputFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateConfigurationFile.
        /// </summary>
        public static string PrivateOutputFileWatermark {
            get {
                return ResourceManager.GetString("PrivateOutputFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists..
        /// </summary>
        public static string PublicOutputFileDoesExist {
            get {
                return ResourceManager.GetString("PublicOutputFileDoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The predefined file extension of the public Document Packer configuration file..
        /// </summary>
        public static string PublicOutputFileExtensionToolTip {
            get {
                return ResourceManager.GetString("PublicOutputFileExtensionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string PublicOutputFileIsRequired {
            get {
                return ResourceManager.GetString("PublicOutputFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Output File.
        /// </summary>
        public static string PublicOutputFileLabel {
            get {
                return ResourceManager.GetString("PublicOutputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the name of the public Document Packer configuration file..
        /// </summary>
        public static string PublicOutputFileToolTip {
            get {
                return ResourceManager.GetString("PublicOutputFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicConfigurationFile.
        /// </summary>
        public static string PublicOutputFileWatermark {
            get {
                return ResourceManager.GetString("PublicOutputFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of the private key is invalid..
        /// </summary>
        public static string RsaPrivateKeyFormatError {
            get {
                return ResourceManager.GetString("RsaPrivateKeyFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private RSA key is required..
        /// </summary>
        public static string RsaPrivateKeyIsRequired {
            get {
                return ResourceManager.GetString("RsaPrivateKeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Private Key.
        /// </summary>
        public static string RsaPrivateKeyLabel {
            get {
                return ResourceManager.GetString("RsaPrivateKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pem formatted private RSA key:
        ///
        ///-----BEGIN RSA PRIVATE KEY-----
        ///MIIJJwIBAAKCAgEAwYzNBVaGz1XT...
        ///-----END RSA PRIVATE KEY-----.
        /// </summary>
        public static string RsaPrivateKeyToolTip {
            get {
                return ResourceManager.GetString("RsaPrivateKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEM formatted private RSA key.
        /// </summary>
        public static string RsaPrivateKeyWatermark {
            get {
                return ResourceManager.GetString("RsaPrivateKeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the RSA public key..
        /// </summary>
        public static string RsaPublicKeyButtonToolTip {
            get {
                return ResourceManager.GetString("RsaPublicKeyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format of the public key is invalid..
        /// </summary>
        public static string RsaPublicKeyFormatError {
            get {
                return ResourceManager.GetString("RsaPublicKeyFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public RSA key is required..
        /// </summary>
        public static string RsaPublicKeyIsRequired {
            get {
                return ResourceManager.GetString("RsaPublicKeyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Public Key.
        /// </summary>
        public static string RsaPublicKeyLabel {
            get {
                return ResourceManager.GetString("RsaPublicKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pem formatted public RSA key:
        ///
        ///-----BEGIN RSA PUBLIC KEY-----
        ///MIICCgKCAgEA...
        ///-----END RSA PUBLIC KEY-----.
        /// </summary>
        public static string RsaPublicKeyToolTip {
            get {
                return ResourceManager.GetString("RsaPublicKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEM formatted public RSA key.
        /// </summary>
        public static string RsaPublicKeyWatermark {
            get {
                return ResourceManager.GetString("RsaPublicKeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the Document Packer configuration in progress..
        /// </summary>
        public static string SaveCancelInfoText {
            get {
                return ResourceManager.GetString("SaveCancelInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured..
        /// </summary>
        public static string SaveCommandUnknownError {
            get {
                return ResourceManager.GetString("SaveCommandUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create configuration files..
        /// </summary>
        public static string SaveConfigurationFails {
            get {
                return ResourceManager.GetString("SaveConfigurationFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files created..
        /// </summary>
        public static string SaveConfigurationSucceeds {
            get {
                return ResourceManager.GetString("SaveConfigurationSucceeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the public and private configuration files..
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select..
        /// </summary>
        public static string SelectedConfigurationItemTypeMissing {
            get {
                return ResourceManager.GetString("SelectedConfigurationItemTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a list of required files and information. Save the list as a configuration and share it with other Document Packer users..
        /// </summary>
        public static string ViewDescription {
            get {
                return ResourceManager.GetString("ViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Configuration.
        /// </summary>
        public static string ViewHeadline {
            get {
                return ResourceManager.GetString("ViewHeadline", resourceCulture);
            }
        }
    }
}
