//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Parts.Main.EncryptPart.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EncryptPartTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncryptPartTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Parts.Main.EncryptPart.Translations.EncryptPartTranslation", typeof(EncryptPartTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new item..
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a file..
        /// </summary>
        public static string AttachFileToolTip {
            get {
                return ResourceManager.GetString("AttachFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ConfigurationItemModelFileLabel {
            get {
                return ResourceManager.GetString("ConfigurationItemModelFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file..
        /// </summary>
        public static string ConfigurationItemModelFileToolTip {
            get {
                return ResourceManager.GetString("ConfigurationItemModelFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file..
        /// </summary>
        public static string ConfigurationItemModelFileWatermark {
            get {
                return ResourceManager.GetString("ConfigurationItemModelFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ConfigurationItemModelTextLabel {
            get {
                return ResourceManager.GetString("ConfigurationItemModelTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the text..
        /// </summary>
        public static string ConfigurationItemModelTextToolTip {
            get {
                return ResourceManager.GetString("ConfigurationItemModelTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ConfigurationItemModelTextWatermark {
            get {
                return ResourceManager.GetString("ConfigurationItemModelTextWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string DataTypeLabel {
            get {
                return ResourceManager.GetString("DataTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the item..
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to encrypt files and information? Generate your personal keys for encryption. Create an encrypted Document Packer file and send it to your friends..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer File.
        /// </summary>
        public static string DocumentPackerFile {
            get {
                return ResourceManager.GetString("DocumentPackerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string EncryptItemTypeFile {
            get {
                return ResourceManager.GetString("EncryptItemTypeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string EncryptItemTypeText {
            get {
                return ResourceManager.GetString("EncryptItemTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        public static string FileIsRequired {
            get {
                return ResourceManager.GetString("FileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name..
        /// </summary>
        public static string FileNameIsMissing {
            get {
                return ResourceManager.GetString("FileNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new RSA public and private key pair..
        /// </summary>
        public static string GenerateRsaKeys {
            get {
                return ResourceManager.GetString("GenerateRsaKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Required.
        /// </summary>
        public static string IsRequiredLabel {
            get {
                return ResourceManager.GetString("IsRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files and Plain-Text.
        /// </summary>
        public static string ItemsHeadline {
            get {
                return ResourceManager.GetString("ItemsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string ItemTypeComboBoxWatermark {
            get {
                return ResourceManager.GetString("ItemTypeComboBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file exists.
        /// </summary>
        public static string OutputFileExists {
            get {
                return ResourceManager.GetString("OutputFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File is required.
        /// </summary>
        public static string OutputFileIsRequired {
            get {
                return ResourceManager.GetString("OutputFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string OutputFileLabel {
            get {
                return ResourceManager.GetString("OutputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file..
        /// </summary>
        public static string OutputFileToolTip {
            get {
                return ResourceManager.GetString("OutputFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file.
        /// </summary>
        public static string OutputFileWatermark {
            get {
                return ResourceManager.GetString("OutputFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder does not exist..
        /// </summary>
        public static string OutputFolderDoesNotExist {
            get {
                return ResourceManager.GetString("OutputFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder is required.
        /// </summary>
        public static string OutputFolderIsRequired {
            get {
                return ResourceManager.GetString("OutputFolderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderLabel {
            get {
                return ResourceManager.GetString("OutputFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output folder of the document packer file..
        /// </summary>
        public static string OutputFolderToolTip {
            get {
                return ResourceManager.GetString("OutputFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string OutputFolderWatermark {
            get {
                return ResourceManager.GetString("OutputFolderWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Keys.
        /// </summary>
        public static string RsaKeys {
            get {
                return ResourceManager.GetString("RsaKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA private key in PEM format..
        /// </summary>
        public static string RsaPrivateKeyToolTip {
            get {
                return ResourceManager.GetString("RsaPrivateKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA public key in PEM format..
        /// </summary>
        public static string RsaPublicKeyToolTip {
            get {
                return ResourceManager.GetString("RsaPublicKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCommandLabel {
            get {
                return ResourceManager.GetString("SaveCommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCommandToolTip {
            get {
                return ResourceManager.GetString("SaveCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle die öffentliche Document Packer Konfigurationsdatei aus.
        /// </summary>
        public static string SelectConfigurationFileCommandToolTip {
            get {
                return ResourceManager.GetString("SelectConfigurationFileCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file..
        /// </summary>
        public static string SelectFileCommandToolTip {
            get {
                return ResourceManager.GetString("SelectFileCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Document Packer file..
        /// </summary>
        public static string SelectOutputFileToolTip {
            get {
                return ResourceManager.GetString("SelectOutputFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the output folder of the document packer file..
        /// </summary>
        public static string SelectOutputFolderToolTip {
            get {
                return ResourceManager.GetString("SelectOutputFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is required..
        /// </summary>
        public static string TextIsRequired {
            get {
                return ResourceManager.GetString("TextIsRequired", resourceCulture);
            }
        }
    }
}
