//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Parts.SubParts.LoadConfigurationSubPart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoadConfigurationTranslation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoadConfigurationTranslation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Parts.SubParts.LoadConfigurationSubPart.LoadConfigurationTranslati" +
                            "on", typeof(LoadConfigurationTranslation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ConfigurationFileDoesNotExist {
            get {
                return ResourceManager.GetString("ConfigurationFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Configuration File.
        /// </summary>
        internal static string ConfigurationFileLabelPrivate {
            get {
                return ResourceManager.GetString("ConfigurationFileLabelPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Configuration File.
        /// </summary>
        internal static string ConfigurationFileLabelPublic {
            get {
                return ResourceManager.GetString("ConfigurationFileLabelPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer configuration file..
        /// </summary>
        internal static string ConfigurationFileToolTip {
            get {
                return ResourceManager.GetString("ConfigurationFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.private.dpc.
        /// </summary>
        internal static string ConfigurationFileWatermarkPrivate {
            get {
                return ResourceManager.GetString("ConfigurationFileWatermarkPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.public.dpc.
        /// </summary>
        internal static string ConfigurationFileWatermarkPublic {
            get {
                return ResourceManager.GetString("ConfigurationFileWatermarkPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LoadConfigurationCommandExecuteAsyncErrorCaption {
            get {
                return ResourceManager.GetString("LoadConfigurationCommandExecuteAsyncErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry: {0}.
        /// </summary>
        internal static string LoadConfigurationCommandExecuteAsyncErrorMessage {
            get {
                return ResourceManager.GetString("LoadConfigurationCommandExecuteAsyncErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadConfigurationCommandLabel {
            get {
                return ResourceManager.GetString("LoadConfigurationCommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Document Packer configuration file..
        /// </summary>
        internal static string LoadConfigurationCommandToolTip {
            get {
                return ResourceManager.GetString("LoadConfigurationCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to encrypt the Document Packer configuration file..
        /// </summary>
        internal static string PasswordToolTip {
            get {
                return ResourceManager.GetString("PasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
    }
}
