//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLinkPartBack {
            get {
                return ResourceManager.GetString("BackLinkPartBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language of the application..
        /// </summary>
        public static string BackLinkPartChangeLanguage {
            get {
                return ResourceManager.GetString("BackLinkPartChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now?.
        /// </summary>
        public static string BackLinkPartRestartCaption {
            get {
                return ResourceManager.GetString("BackLinkPartRestartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the language you must restart the application. Would you like to restart now?.
        /// </summary>
        public static string BackLinkPartRestartRequest {
            get {
                return ResourceManager.GetString("BackLinkPartRestartRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Document Packer language settings and select a different language..
        /// </summary>
        public static string ChangeLanguagePartDescription {
            get {
                return ResourceManager.GetString("ChangeLanguagePartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string ChangeLanguagePartHeadline {
            get {
                return ResourceManager.GetString("ChangeLanguagePartHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer.
        /// </summary>
        public static string DocumentPacker {
            get {
                return ResourceManager.GetString("DocumentPacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentPacker (en).
        /// </summary>
        public static string DocumentPackerPartTitle {
            get {
                return ResourceManager.GetString("DocumentPackerPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string DocumentPackerPartVersion {
            get {
                return ResourceManager.GetString("DocumentPackerPartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create configuration.
        /// </summary>
        public static string EncryptStartUpPartCreateConfiguration {
            get {
                return ResourceManager.GetString("EncryptStartUpPartCreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a DocumentPacker configuration file..
        /// </summary>
        public static string EncryptStartUpPartCreateConfigurationDescription {
            get {
                return ResourceManager.GetString("EncryptStartUpPartCreateConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration.
        /// </summary>
        public static string EncryptStartUpPartLoadConfiguration {
            get {
                return ResourceManager.GetString("EncryptStartUpPartLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a DocumentPacker configuration file, pack and encrypt files..
        /// </summary>
        public static string EncryptStartUpPartLoadConfigurationDescription {
            get {
                return ResourceManager.GetString("EncryptStartUpPartLoadConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a list of required files and information. Save the list as a configuration and share it with other Document Packer users..
        /// </summary>
        public static string FeaturesPartCreateConfigDescription {
            get {
                return ResourceManager.GetString("FeaturesPartCreateConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Configuration.
        /// </summary>
        public static string FeaturesPartCreateConfigHeadline {
            get {
                return ResourceManager.GetString("FeaturesPartCreateConfigHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been sent an encrypted Document Packer file?
        ///Decrypt the Document Packer file with your private key. View or save the decrypted files.
        ///
        ///.
        /// </summary>
        public static string FeaturesPartDecryptDescription {
            get {
                return ResourceManager.GetString("FeaturesPartDecryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string FeaturesPartDecryptHeadline {
            get {
                return ResourceManager.GetString("FeaturesPartDecryptHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to encrypt files and information? Generate your personal keys for encryption. Create an encrypted Document Packer file and send it to your friends..
        /// </summary>
        public static string FeaturesPartEncryptDescription {
            get {
                return ResourceManager.GetString("FeaturesPartEncryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string FeaturesPartEncryptHeadline {
            get {
                return ResourceManager.GetString("FeaturesPartEncryptHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! What can we do for you?.
        /// </summary>
        public static string FeaturesPartHeadline {
            get {
                return ResourceManager.GetString("FeaturesPartHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}.
        /// </summary>
        public static string FooterPartVersion {
            get {
                return ResourceManager.GetString("FooterPartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer.
        /// </summary>
        public static string HeaderPartHeadline {
            get {
                return ResourceManager.GetString("HeaderPartHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string StartUpPartDecrypt {
            get {
                return ResourceManager.GetString("StartUpPartDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt documents and text..
        /// </summary>
        public static string StartUpPartDecryptDescription {
            get {
                return ResourceManager.GetString("StartUpPartDecryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string StartUpPartEncrypt {
            get {
                return ResourceManager.GetString("StartUpPartEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt documents and text..
        /// </summary>
        public static string StartUpPartEncryptDescription {
            get {
                return ResourceManager.GetString("StartUpPartEncryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer.
        /// </summary>
        public static string WindowPartTitle {
            get {
                return ResourceManager.GetString("WindowPartTitle", resourceCulture);
            }
        }
    }
}
