//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentPacker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentPacker.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension of the archive entry..
        /// </summary>
        public static string ArchiveIdExtensionToolTip {
            get {
                return ResourceManager.GetString("ArchiveIdExtensionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id of the archive entry..
        /// </summary>
        public static string ArchiveIdToolTip {
            get {
                return ResourceManager.GetString("ArchiveIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language of the application..
        /// </summary>
        public static string BackLinkPartChangeLanguage {
            get {
                return ResourceManager.GetString("BackLinkPartChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Packer.
        /// </summary>
        public static string DocumentPacker {
            get {
                return ResourceManager.GetString("DocumentPacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentPacker (en).
        /// </summary>
        public static string DocumentPackerPartTitle {
            get {
                return ResourceManager.GetString("DocumentPackerPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string DocumentPackerPartVersion {
            get {
                return ResourceManager.GetString("DocumentPackerPartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EncryptPartDescriptionLabel {
            get {
                return ResourceManager.GetString("EncryptPartDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt &amp; Pack.
        /// </summary>
        public static string EncryptPartEncrypt {
            get {
                return ResourceManager.GetString("EncryptPartEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        public static string EncryptPartFileDoesNotExists {
            get {
                return ResourceManager.GetString("EncryptPartFileDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file..
        /// </summary>
        public static string EncryptPartFileIsRequired {
            get {
                return ResourceManager.GetString("EncryptPartFileIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string EncryptPartId {
            get {
                return ResourceManager.GetString("EncryptPartId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Required.
        /// </summary>
        public static string EncryptPartIsRequiredLabel {
            get {
                return ResourceManager.GetString("EncryptPartIsRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Private Key.
        /// </summary>
        public static string EncryptPartRsaPrivateKey {
            get {
                return ResourceManager.GetString("EncryptPartRsaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Public Key.
        /// </summary>
        public static string EncryptPartRsaPublicKey {
            get {
                return ResourceManager.GetString("EncryptPartRsaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a custom text..
        /// </summary>
        public static string EncryptPartTextIsRequired {
            get {
                return ResourceManager.GetString("EncryptPartTextIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create configuration.
        /// </summary>
        public static string EncryptStartUpPartCreateConfiguration {
            get {
                return ResourceManager.GetString("EncryptStartUpPartCreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a DocumentPacker configuration file..
        /// </summary>
        public static string EncryptStartUpPartCreateConfigurationDescription {
            get {
                return ResourceManager.GetString("EncryptStartUpPartCreateConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration.
        /// </summary>
        public static string EncryptStartUpPartLoadConfiguration {
            get {
                return ResourceManager.GetString("EncryptStartUpPartLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a DocumentPacker configuration file, pack and encrypt files..
        /// </summary>
        public static string EncryptStartUpPartLoadConfigurationDescription {
            get {
                return ResourceManager.GetString("EncryptStartUpPartLoadConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1}.
        /// </summary>
        public static string FooterPartVersion {
            get {
                return ResourceManager.GetString("FooterPartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string StartUpPartDecrypt {
            get {
                return ResourceManager.GetString("StartUpPartDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt documents and text..
        /// </summary>
        public static string StartUpPartDecryptDescription {
            get {
                return ResourceManager.GetString("StartUpPartDecryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string StartUpPartEncrypt {
            get {
                return ResourceManager.GetString("StartUpPartEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt documents and text..
        /// </summary>
        public static string StartUpPartEncryptDescription {
            get {
                return ResourceManager.GetString("StartUpPartEncryptDescription", resourceCulture);
            }
        }
    }
}
